### ISSUE TITLE
Is it possible to use stabmap to integrate separate atac and rna data? 

### ISSUE THREAD

**Issue by Chengwei94** [MarioniLab/StabMap#3]
Hi there, 
I have 2 dataset of atac and rna done separately. Is it possible to use stabmap to integrate them together? Thanks!

**Comment by shazanfar** [comment]
Hi Chengwei, for your data if it is atac and rna done separately it would be considered a 'diagonal integration'. You could assume that the atac peaks and rna genes match in some way and then implement StabMap under this assumption, otherwise I would suggest a method such as [scJoint](https://www.nature.com/articles/s41587-021-01161-6). Hope that helps!
